kind:service
apiVersion: v1
metadata:
  name: docker-service
  namespace: docker-namespace
spec:
  selector:
    app: docker-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort